# Especifica a versão da sintaxe do arquivo Docker Compose
version: '3.7'

# Declara os volumes
volumes:
  n8n_data:
  postgres_data:

# Declara as redes virtuais
networks:
  n8n-network:
    driver: bridge

# Define a lista de todos os containers
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=n8n          # Corrigido: era POSTG-RES_USER
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n-network

  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    depends_on:
      - postgres
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=root
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - GENERIC_TIMEZONE=America/Sao_Paulo
      # Configuração para nós customizados
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
    volumes:
      - n8n_data:/home/node/.n8n
      # Mapeamento do projeto customizado
      - ./dist:/home/node/.n8n/custom
      # Alternativa: mapear todo o projeto
      # - ./:/home/node/.n8n/custom
    networks:
      - n8n-network
